server {
    listen 80;
    server_name localhost;

    # Frontend: Serve Angular static files
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Backend: Proxy API requests to the API container
    location /api/ {
        proxy_pass http://repair_nest:3000/; # Replace with your API container name and internal port
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}